---
title: "Mirror"
author: Roland kaiser
date: 2020-01-06
output: md_document
---

<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{RMarkdown Citations - Alphabetic Style}
-->

```{r setup, include = TRUE, echo = FALSE, cache = FALSE}
library(vegsoup)
library(RefManageR)

BibOptions(check.entries = FALSE, style = "markdown",
cite.style = "draft", bib.style = "draft")

path <- "~/Documents/vegsoup-data"
x <- list.files(path)

#	files to ignore
ii <- c(
#	other files
	"CHANGES.md",
	"README.md",
	"README.png",	
	"mirror",
	"givd",	# to be deleted
#	unfished data sets
	"dirnböck1999",
	"brunner2011",
	"dunzendorfer1980",
	"greimler1996",
	"greimler1997",
	"grims1982",
	"hohewand fence dta",
	"hohewand transect dta",
	"jakubowsky1996",
	"monte negro dta",
	"nußbaumer2000",
	"pflugbeil2012",
	"prebersee dta",
	"ruttner1994",
	"sobotik1998",
	"schwarz1989",
	"stadler1991", # to be deleted
	"stadler1992", # to be deleted
	"surina2004",
#	occurrence plots only
	"alt ems dta",
	"adnet dta",
	"bräumauer dta",
	"glasenbachklamm dta",
	"graswang dta",
	"illschlucht dta",
	"jansenmäuer dta",
	"kreuzmauer dta",
	"lichtl dta",
	"luegstein dta",
	"montikel dta",
	"priental dta",
	"reitnerkogel dta",
	"schartenmauer dta",
	"schieferstein dta",
	"schrattenboden dta",
	"wirlingwand dta",
	"ybbs and türnitz prealps dta",
	"zwurms meschach dta",	
#	independent taxonomy
	"crete dta",
	"javakheti dta",
	"cape hallet lichen dta",
	"salzkammergut lichen dta",
	"kalkalpen lichen dta",
#	custom coverscale and taxonomy
	"furka dta",		
#	turboveg taxonomy (keep in sync with *mirror turboveg.R*)
	"aspro dta",
	"donauauen dta",
	"enzersfeld dta",
	"fischamend dta",	
	"hainburg dta",
	"kirchdorf and steyr-land dta",
	"mountain hay meadows dta",
	"nackter sattel dta",
	"neusiedlersee dta",
	"pilgersdorf dta",
	"ravine forest dta",	
	"reichraming dta",
	"sankt margarethen dta",
	"seekirchen dta",	
	"südburgenland dta",
	"traun and steyr and ennstal dta",
	"vorarlberg dta",
	"wien dta",
	"wienerwald dta",
	"witzelsdorf dta"
)

s <- match(ii, x)
s <- s[ !is.na(s) ]
x <- x[ -s ]

#	biblographic entities
x <- sapply(file.path(path, x), function (x) {
	ReadBib(file.path(x, "references.bib"))	
}, simplify = FALSE)

#	collect entities
b <- do.call("c", x)
```

Bibliographic references to data sets
=====================================
`r Cite(b)`  


```{r results = "asis", echo = FALSE}
PrintBibliography(b, .opts = list(check.entries = FALSE, bib.style = "draft"))
```